# Generated by Django 4.1.2 on 2023-03-01 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0006_chatmessages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chatMessages',
        ),
    ]
